### ISSUE TITLE
Change location of undo save point

### ISSUE THREAD

**Issue by JoeyChenSmart** [AY2021S1-CS2103T-W17-3/tp#112]
Right now it saves state between each change to the `Model`.

By right it should save state in between each `Command` execution

**Comment by aidoxe-123** [comment]
If the user calls `list` multiple times, what should be the expected behavior of the program? Should it allow undoing the same number as the number of list command, or just 1 time?

**Comment by Jh123x** [comment]
Adding extra stack to store predicate for filtering
