### ISSUE TITLE
Weird undo bug when find returns multiple items

### ISSUE THREAD

**Issue by aidoxe-123** [AY2021S1-CS2103T-W17-3/tp#115]
How to recreate a bug:
- `add -n test 1`
- `add -n test`
- `find test`
- `undo`
=> At this stage, the program will successfully undo and the first test item will be deleted, which is different from what is expected)

To create expected behavior:
- (Any find command that returns one item) (E.g start with a default mcgymmy -> `find Nasi Lemak`)
- `undo`
=> The program announces that you cannot undo anymore

**Comment by JoeyChenSmart** [comment]
likely this is the cause #112 
Also we should make it such that each command is undoable and document this in the UG. Easiest solution
