### ISSUE TITLE
History and ModelManager may have cyclic dependencies

### ISSUE THREAD

**Issue by JoeyChenSmart** [AY2021S1-CS2103T-W17-3/tp#132]
Sounds like a problem, maybe its not.

Can be easily 'fixed' (or alleviated?) if we change `History`'s `save` method to take in a `Model` instead of `ModelManager` (i.e. use the interface).

**Comment by aidoxe-123** [comment]
If `History::save` takes in a Model, the `ModelManager::getPredicate` must be public. However, that method is not supposed to be accessed by classes outside of the package. If we really want to alleviate this problem, we might want to create an association class

**Comment by Jh123x** [comment]
Close as it is not part of code quality.
