### ISSUE TITLE
Refactor Runtime Exception within McGymmy to its respective Exceptions

### ISSUE THREAD

**Issue by Jh123x** [AY2021S1-CS2103T-W17-3/tp#145]

**Comment by JoeyChenSmart** [comment]
Likely if we export a file, edit some carbohydrate value to 500000 and import it, this will cause the app to explode

Have to check if the AB3 storage part catches this

**Comment by JoeyChenSmart** [comment]
The group I tested for dry run PE had a bug because of this. This is worth looking into
