### ISSUE TITLE
Document the behavior of the common-cli library

### ISSUE THREAD

**Issue by aidoxe-123** [AY2021S1-CS2103T-W17-3/tp#199]
Many of the bugs reported are related to the fact that common-cli automatically appends arguments of the same parameter
For example, if the user input `add -n Chicken -p 50 -p 50` , the library will parse "50 50" as an argument for protein, which causes parseInt error

**Comment by Jh123x** [comment]
Hmm while that is true, they can rely on Macro and Tag / untag commands to add tags in succession.
This might tie in together with the default macros issue
