### ISSUE TITLE
Undo feature in DG

### ISSUE THREAD

**Issue by Jh123x** [AY2021S1-CS2103T-W17-3/tp#294]
- [x] Update grammar in implementation section of DG
- [ ] Update UML diagram for Undo to include MacroList
- [x] Grammer in Alternative implementation section

**Comment by dcchan98** [comment]
@Jh123x imo we shouldnt combine all notes into 1

**Comment by Jh123x** [comment]
> @Jh123x imo we shouldnt combine all notes into 1

Hmm ok. I remove the task ba

**Comment by Jh123x** [comment]
Addressed in #298
