### ISSUE TITLE
Increase Granularity of Find Command

### ISSUE THREAD

**Issue by Jh123x** [AY2021S1-CS2103T-W17-3/tp#92]

**Comment by JoeyChenSmart** [comment]
e.g. `find -date 2020-11-11 -tag lunch`
e.g. `find rice -date 2020-11-11 -tag lunch`

**Comment by aidoxe-123** [comment]
Might also add an extension like this:
`find -all [keyword 1] [keyword 2] ...` to find foods that match all of the keywords
`find -some [keyword 1] [keyword 2]...` to find foods that match some of the keywords

**Comment by chewypiano** [comment]
> Might also add an extension like this:
> `find -all [keyword 1] [keyword 2] ...` to find foods that match all of the keywords
> `find -some [keyword 1] [keyword 2]...` to find foods that match some of the keywords

The `find -some` is inherently adopted, as in it works like that currently. The `find -all` looks good, we can probably do so in future if needed.
